src/AppBundle/Entity/Fournisseurs.php
<?php
/**
 * Created by PhpStorm.
 * User: Gaap_
 * Date: 17/06/2018
 * Time: 23:08
 */

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Fournisseurs
 *
 * @ORM\Table(name="fournisseurs", indexes={@ORM\Index(name="id", columns={"id"})})
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FournisseursRepository")
 */
class Fournisseurs
{
    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @ORM\Column("nom", type="string", length=50, nullable=false)
     */
    private $nom;

    /**
     * @ORM\Column("adresse", type="string", length=255, nullable=false)
     */
    private $adresse;

    /**
     * @ORM\Column("siret", type="string", length=16, nullable=false)
     */
    private $siret;

    /**
     * @ORM\Column("active", type="boolean", nullable=false)
     */
    private $is_active;

    /**
     * @ORM\Column("created_at", type="datetime", nullable=false)
     */
    private $created_at;

    /**
     * @ORM\Column("updated_at", type="datetime", nullable=false)
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\FournisseursProduits", mappedBy="fournisseurs")
     */
    private $fournisseurs_produits;

    public function __toString()
    {
        return $this->nom;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * @param mixed $adresse
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;
    }

    /**
     * @return mixed
     */
    public function getSiret()
    {
        return $this->siret;
    }

    /**
     * @param mixed $siret
     */
    public function setSiret($siret)
    {
        $this->siret = $siret;
    }

    /**
     * @return mixed
     */
    public function getisActive()
    {
        return $this->is_active;
    }

    /**
     * @param mixed $is_active
     */
    public function setIsActive($is_active)
    {
        $this->is_active = $is_active;
    }

    /**
     * @return mixed
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param mixed $created_at
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;
    }

    /**
     * @return mixed
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * @param mixed $updated_at
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;
    }

    /**
     * @return mixed
     */
    public function getFournisseursProduits()
    {
        return $this->fournisseurs_produits;
    }

    /**
     * @param mixed $fournisseurs_produits
     */
    public function setFournisseursProduits($fournisseurs_produits)
    {
        $this->fournisseurs_produits = $fournisseurs_produits;
    }



}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="col text-center">
        <h1>Ma poissonnerie</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col text-center"><a href="{{ path('fournisseur_create') }}">
                    <button type="button" class="btn btn-primary">creation fournisseurs</button>
                </a></div>
            <div class="col text-center"><a href="{{ path('produit_create') }}">
                    <button type="button" class="btn btn-primary">creation produits</button>
                </a></div>
        </div>

        <div class="row" style="margin-top: 100px;">
            <div class="col text-center">
                <h2>Mes fournisseurs</h2>
            </div>
        </div>
        {% for fournisseur in fournisseurs %}
            <div class="row" style="margin-bottom: 10px; border-bottom: 1px solid #000; padding-top: 10px; padding-bottom: 10px;">
                <div class="col-6">{{ fournisseur.nom }}</div>
                <div class="col-2">
                    <a data-toggle="collapse" href="#produitsFournisseurs{{ fournisseur.id }}" role="button" aria-expanded="false" aria-controls="produitsFournisseurs{{ fournisseur.id }}">
                        <button type="button" class="btn btn-primary">Ses produits</button>
                    </a>
                </div>
                <div class="col-2">
                    <a href="{{ path('fournisseur_update', {'id' : fournisseur.id }) }}">
                        <button type="button" class="btn btn-primary">Update</button>
                    </a>
                </div>
                <div class="col-2">
                    <a href="{{ path('fournisseur_delete', {'id' : fournisseur.id }) }}">
                        <button type="button" class="btn btn-primary">Delete</button>
                    </a>
                </div>
                <div style="margin-top: 15px; width: 100%;" class="collapse" id="produitsFournisseurs{{ fournisseur.id }}">
                    <div class="card card-body">
                        <div class="row">
                            {% if fournisseur.fournisseursProduits|length %}
                                {% for produit in fournisseur.fournisseursProduits %}
                                    <div class="col-4">
                                        - {{ produit.produits.nom }} <a title="edit" href="{{ path('produit_update', {'id' : produit.produits.id}) }}"><i class="fas fa-edit"></i></a>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="col">Aucun produit.</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="row" style="margin-top: 100px;">
            <div class="col text-center">
                <h2>Mes produits</h2>
            </div>
        </div>
        {% for produit in produits %}
            <div class="row" style="margin-bottom: 10px; border-bottom: 1px solid #000; padding-top: 10px; padding-bottom: 10px;">
                <div class="col-6">{{ produit.nom }}</div>
                <div class="col-2">
                    <a data-toggle="collapse" href="#fournisseursProduits{{ produit.id }}" role="button" aria-expanded="false" aria-controls="fournisseursProduits{{ produit.id }}">
                        <button type="button" class="btn btn-primary">Les fournisseurs</button>
                    </a>
                </div>
                <div class="col-2">
                    <a href="{{ path('produit_update', {'id' : produit.id }) }}">
                        <button type="button" class="btn btn-primary">Update</button>
                    </a>
                </div>
                <div class="col-2">
                    <a href="{{ path('produit_delete', {'id' : produit.id }) }}">
                        <button type="button" class="btn btn-primary">Delete</button>
                    </a>
                </div>
                <div style="margin-top: 15px; width: 100%;" class="collapse" id="fournisseursProduits{{ produit.id }}">
                    <div class="card card-body">
                        <div class="row">
                            {% if produit.produitsFournisseurs|length %}
                                {% for fournisseur in produit.produitsFournisseurs %}
                                    <div class="col-4">
                                        - {{ fournisseur.fournisseurs.nom }} <a title="edit" href="{{ path('fournisseur_update', {'id' : fournisseur.fournisseurs.id }) }}"><i class="fas fa-edit"></i></a>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="col">Aucun fournisseur.</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
{% endblock %}